name: ccrouter_workspace
publish_to: none
environment:
  sdk: ^3.10.0

dev_dependencies:
  build_runner: ^2.10.0
  test: ^1.26.0

workspace:
  - packages/ccrouter_contracts
  - packages/ccrouter_analytics
  - packages/ccrouter_auto_track
  - packages/ccrouter_core
  - packages/ccrouter
  - packages/ccrouter_go_router
  - packages/ccrouter_generator
  - packages/ccrouter_test
  - demo
  - demo/modules/order
  - demo/modules/order_contracts
  - demo/modules/payment
  - demo/modules/navigation_lab
  - demo/modules/web_contracts
  - demo/modules/web
