import 'package:ccrouter/ccrouter.dart';
import 'package:flutter/widgets.dart';
import 'package:go_router/go_router.dart';

import 'route_binding.dart';
import 'navigation_observer.dart';
import 'shell_binding.dart';

part 'foreign_route_bridge.dart';

/// Adapts CCRouter navigation requests to an externally configured [GoRouter].
///
/// The application owns the [router] and supplies its `GoRoute` page builders.
/// This adapter only translates validated CCRouter operations; it does not
/// generate page widgets, retain a global `BuildContext`, or dispose the
/// externally supplied router. GoRouter route paths should match the primary
/// path patterns generated by the registered route contracts.
///
/// Modal bottom sheets and dialogs are supported when their bound [GoRoute]
/// supplies a custom `pageBuilder` returning the corresponding exported modal
/// Page type. The adapter does not rewrite application-owned GoRoutes.
final class CCGoRouterAdapter
    implements
        CCNavigationAdapter,
        CCNavigationAdapterCapabilitySource,
        CCNavigationBackendEventSource,
        CCNavigationBackendSnapshotSource,
        CCNavigationPopCoordinator {
  /// Creates an adapter around an application-owned [router].
  factory CCGoRouterAdapter({
    required GoRouter router,
    Iterable<CCGoRouterRouteBinding> bindings = const [],
    Iterable<CCGoRouterShellBinding> shells = const [],
    Map<String, GlobalKey<NavigatorState>> navigatorKeys = const {},
    Iterable<CCGoRouterNavigationObserver> observers = const [],
    int lifecycleEventCapacity = 1000,
  }) {
    final shellList = List<CCGoRouterShellBinding>.unmodifiable(shells);
    final observerList = List<CCGoRouterNavigationObserver>.unmodifiable(
      observers,
    );
    return CCGoRouterAdapter._(
      router: router,
      bindings: bindings,
      shells: shellList,
      navigatorKeys: navigatorKeys,
      observers: observerList,
      lifecycleEventCapacity: lifecycleEventCapacity,
    );
  }

  /// Internal constructor used after iterable inputs have been snapshotted.
  CCGoRouterAdapter._({
    required GoRouter router,
    required Iterable<CCGoRouterRouteBinding> bindings,
    required Iterable<CCGoRouterShellBinding> shells,
    required Map<String, GlobalKey<NavigatorState>> navigatorKeys,
    required Iterable<CCGoRouterNavigationObserver> observers,
    required int lifecycleEventCapacity,
  }) : _router = router,
       _bindings = List.unmodifiable(bindings),
       _shellBindings = List.unmodifiable(shells),
       _navigatorKeys = _mergeNavigatorKeys(navigatorKeys, shells),
       _observers = List.unmodifiable(observers),
       _lifecycleEventCapacity = lifecycleEventCapacity {
    if (lifecycleEventCapacity < 0) {
      throw ArgumentError.value(
        lifecycleEventCapacity,
        'lifecycleEventCapacity',
        'Capacity cannot be negative.',
      );
    }
    _foreignRouteBridge = CCGoRouterForeignRouteBridge._(
      allocateBackendEntryId: _nextBackendEntryId,
      publish: _recordForeignBridgeEvent,
      publishOpaque: _recordOpaqueBridgeEvent,
    );
    for (final observer in _observers) {
      _observerRemovers.add(observer.addListener(_recordLifecycleEvent));
    }
  }

  /// GoRouter instance that receives translated navigation operations.
  GoRouter get router => _router;

  /// Backend capabilities exposed for Host setup and diagnostics.
  ///
  /// The supplied GoRouter remains application-owned, so predictive-back
  /// coordination is not claimed until a future integration provides those
  /// signals. Its current match tree and initial route-information location
  /// can still be reported as opaque backend entries.
  @override
  CCNavigationAdapterCapabilities get capabilities =>
      const CCNavigationAdapterCapabilities(
        supportsForeignEntryObservation: true,
        supportsBackendEntryIdentity: true,
        supportsInitialStackSnapshot: true,
        supportsAtomicPopAndPush: true,
        supportsPushAndRemoveUntil: true,
        supportsNestedNavigators: true,
        supportsStatefulShell: true,
        supportsModalRoutes: true,
        supportsOpaqueUiObservation: true,
      );

  /// Host-only bridge for explicitly integrated third-party Navigator routes.
  ///
  /// Application composition roots may use this when an independent Navigator
  /// cannot install [CCGoRouterNavigationObserver]. Business features should
  /// continue to navigate only through `CCRouter.navigator`.
  CCGoRouterForeignRouteBridge get foreignRouteBridge => _foreignRouteBridge;

  /// Reads GoRouter's pre-existing match tree as opaque backend entries.
  ///
  /// The initial match tree has no CCRouter `navigationId`, so every entry is
  /// intentionally classified as opaque. Runtime can diagnose the existing
  /// GoRouter stack and its Shell Outlets, but it cannot create a managed
  /// RouteEntry or typed result channel from this snapshot.
  @override
  Future<List<CCNavigationBackendEntrySnapshot>>
  readInitialBackendSnapshot() async {
    _ensureAvailable();
    final snapshots = <CCNavigationBackendEntrySnapshot>[];
    _collectInitialMatches(
      _router.routerDelegate.currentConfiguration.matches,
      snapshots,
      outlet: 'root',
    );
    if (snapshots.isEmpty) {
      final initialUri = _router.routeInformationProvider.value.uri;
      if (initialUri.toString().isNotEmpty) {
        snapshots.add(
          CCNavigationBackendEntrySnapshot(
            backendEntryId: _nextBackendEntryId(),
            owner: CCBackendEntryOwner.opaque,
            navigatorOutlet: 'root',
            location: initialUri.toString(),
          ),
        );
      }
    }
    return List.unmodifiable(snapshots);
  }

  /// Application-owned GoRouter backend.
  final GoRouter _router;

  /// Adapter-owned third-party route reporting bridge.
  late final CCGoRouterForeignRouteBridge _foreignRouteBridge;

  /// Component route bindings used to validate the application route table.
  final List<CCGoRouterRouteBinding> _bindings;

  /// Application-owned Shell bindings used to validate placement metadata.
  final List<CCGoRouterShellBinding> _shellBindings;

  /// Runtime Shell contracts accepted during initialization.
  final List<CCNavigationShell> _runtimeShells = [];

  /// Application-owned Navigator keys indexed by CCRouter Outlet name.
  final Map<String, GlobalKey<NavigatorState>> _navigatorKeys;

  /// Observers supplied by the application-owned GoRouter tree.
  final List<CCGoRouterNavigationObserver> _observers;

  /// Maximum number of lifecycle events retained for diagnostics.
  final int _lifecycleEventCapacity;

  /// Listener removers registered against [_observers].
  final List<void Function()> _observerRemovers = [];

  /// Runtime listeners receiving backend Navigator observations.
  final Set<CCNavigationBackendEventListener> _backendListeners = {};

  /// Bounded lifecycle events emitted by configured Navigator observers.
  final List<CCGoRouterNavigationEvent> _lifecycleEvents = [];

  /// Route metadata accepted by the Runtime during initialization.
  final List<CCNavigationRoute> _routes = [];

  /// Entries observed through operations issued by this adapter.
  final List<_CCGoRouterEntry> _entries = [];

  /// Adapter-local prefix used to keep backend identities unique across
  /// multiple GoRouter adapters in one process.
  final String _backendAdapterId =
      '${DateTime.now().microsecondsSinceEpoch}-${identityHashCode(Object())}';

  /// Monotonic backend Entry sequence for this adapter instance.
  int _backendEntrySequence = 0;

  /// Monotonic backend operation sequence for this adapter instance.
  int _backendOperationSequence = 0;

  /// Identity map from Flutter Routes to backend Entry IDs.
  final Expando<String> _backendRouteIds = Expando<String>();

  /// Backend Entry ID observed by the most recent Pop callback.
  String? _lastPoppedBackendEntryId;

  /// Ownership observed for the most recent Pop callback.
  CCPopRemovedOwner _lastPoppedOwner = CCPopRemovedOwner.none;

  /// Managed backend IDs indexed by their Runtime navigation identity.
  final Map<String, String> _backendIdsByNavigationId = {};

  /// Backend transitions expected from the next adapter-owned operations.
  ///
  /// Navigator observer callbacks may arrive after the imperative call has
  /// returned, so a short-lived queue is safer than a synchronous mutation
  /// flag for distinguishing adapter-owned transitions from external changes.
  final List<CCGoRouterNavigationEventKind> _expectedBackendEvents = [];

  /// Whether [initialize] completed successfully.
  bool _initialized = false;

  /// Whether [dispose] permanently closed the adapter.
  bool _disposed = false;

  /// Whether the adapter is initialized and has not been disposed.
  bool get isInitialized => _initialized && !_disposed;

  /// Immutable route metadata accepted during initialization.
  List<CCNavigationRoute> get routes => List.unmodifiable(_routes);

  /// Application-owned GoRouter bindings supplied for Runtime route IDs.
  List<CCGoRouterRouteBinding> get bindings => _bindings;

  /// Navigator keys used to resolve explicit non-root Outlet targets.
  Map<String, GlobalKey<NavigatorState>> get navigatorKeys => _navigatorKeys;

  /// Application-owned Shell bindings supplied for Runtime route placement.
  List<CCGoRouterShellBinding> get shells => _shellBindings;

  /// Runtime Shell contracts validated against application-owned bindings.
  List<CCNavigationShell> get shellContracts =>
      List.unmodifiable(_runtimeShells);

  /// Navigator observers subscribed by this Adapter.
  List<CCGoRouterNavigationObserver> get observers => _observers;

  /// Bounded snapshot of observed Navigator lifecycle events.
  List<CCGoRouterNavigationEvent> get lifecycleEvents =>
      List.unmodifiable(_lifecycleEvents);

  /// Subscribes to backend Navigator transitions observed by this adapter.
  ///
  /// Runtime uses this optional adapter capability to expose user gesture,
  /// system back, and application-owned stack changes without importing
  /// Flutter types into Core. The returned callback removes the listener.
  @override
  void Function() addBackendEventListener(
    CCNavigationBackendEventListener listener,
  ) {
    _backendListeners.add(listener);
    return () => _backendListeners.remove(listener);
  }

  /// Initializes the adapter with Runtime-validated route metadata.
  ///
  /// The adapter validates presentation capabilities before accepting any
  /// navigation. GoRouter remains responsible for matching and rendering the
  /// application's concrete `GoRoute` tree.
  @override
  Future<void> initialize(
    List<CCNavigationRoute> routes, {
    List<CCNavigationShell> shells = const [],
  }) async {
    _ensureNotDisposed();
    if (_initialized) {
      throw const CCNavigationAdapterError(
        'The GoRouter navigation adapter is already initialized.',
      );
    }
    final routeIds = <String>{};
    _validateShellBindings(shells);
    _runtimeShells
      ..clear()
      ..addAll(shells);
    for (final route in routes) {
      if (!routeIds.add(route.routeId)) {
        throw CCNavigationAdapterError(
          'Duplicate route ID "${route.routeId}" supplied to GoRouter.',
        );
      }
      switch (route.presentation) {
        case final CCPagePresentation presentation:
          _validatePresentationBinding(
            route.routeId,
            CCGoRouterPresentationType.page,
          );
          if (_requiresCustomPage(presentation)) {
            _ensureCustomPage(route.routeId);
          }
          break;
        case CCModalBottomSheetPresentation():
          _validatePresentationBinding(
            route.routeId,
            CCGoRouterPresentationType.bottomSheet,
          );
          _ensureCustomModalPage(route.routeId);
          break;
        case CCDialogPresentation():
          _validatePresentationBinding(
            route.routeId,
            CCGoRouterPresentationType.dialog,
          );
          _ensureCustomModalPage(route.routeId);
      }
      _validatePlacement(route);
    }
    _validateBindings(routeIds);
    _routes
      ..clear()
      ..addAll(routes);
    _initialized = true;
  }

  /// Executes one validated request through GoRouter.
  @override
  Future<Object?> navigate(CCNavigationRequest request) {
    _ensureAvailable();
    _ensureRoute(request.routeId);
    final location = _locationFor(request.uri);
    switch (request.operation) {
      case CCNavigationOperation.push:
        return _push(request, location);
      case CCNavigationOperation.replace:
        return _replace(request, location);
      case CCNavigationOperation.go:
      case CCNavigationOperation.reset:
      case CCNavigationOperation.open:
        _expectBackendEvent(CCGoRouterNavigationEventKind.remove);
        _expectBackendEvent(CCGoRouterNavigationEventKind.push);
        _router.go(location, extra: request.extra);
        _replaceTrackedStack(request);
        return Future<Object?>.value();
      case CCNavigationOperation.popAndPush:
      case CCNavigationOperation.pushAndRemoveUntil:
        throw const CCNavigationAdapterError(
          'Composite operations must use their dedicated Adapter method.',
        );
    }
  }

  /// Attempts to pop the active GoRouter Navigator route.
  ///
  /// A successful `Navigator.maybePop` can consume a LocalHistoryEntry or a
  /// foreign PopupRoute instead of an adapter-owned route. The managed entry
  /// list is therefore not changed by position here; a result-bearing managed
  /// Push removes its own entry when the GoRouter Future completes.
  @override
  Future<bool> maybePop({Object? result}) async {
    final outcome = await maybePopOutcome(result: result);
    return outcome.handled;
  }

  /// Coordinates a GoRouter Pop with best-effort backend identity correlation.
  ///
  /// A Pop with no Navigator observer event is reported as handled with owner
  /// `none`; this is the expected result for LocalHistoryEntry and opaque
  /// backend guards, and it never causes Runtime to remove a managed entry.
  @override
  Future<CCPopOutcome> maybePopOutcome({Object? result}) async {
    _ensureAvailable();
    final navigator = _activeNavigator;
    if (navigator == null) return const CCPopOutcome(handled: false);
    _lastPoppedBackendEntryId = null;
    _lastPoppedOwner = CCPopRemovedOwner.none;
    _expectBackendEvent(CCGoRouterNavigationEventKind.pop);
    final didPop = await navigator.maybePop<Object?>(result);
    // LocalHistoryEntry consumption emits no NavigatorObserver Pop. Remove an
    // unmatched expectation before it can misclassify a later foreign Pop.
    _discardExpectedBackendEvent(CCGoRouterNavigationEventKind.pop);
    if (!didPop) return const CCPopOutcome(handled: false);
    return CCPopOutcome(
      handled: true,
      removedBackendEntryId: _lastPoppedBackendEntryId,
      removedOwner: _lastPoppedOwner,
      resultAvailable: _lastPoppedOwner == CCPopRemovedOwner.managed,
    );
  }

  /// Pops the active entry and pushes [request] through GoRouter.
  ///
  /// GoRouter exposes no single public operation with this exact contract, so
  /// the adapter performs the Pop through GoRouter's active Navigator and then
  /// issues its imperative Push. The removed entry receives [popResult].
  @override
  Future<Object?> popAndPush(
    CCNavigationRequest request, {
    Object? popResult,
  }) async {
    _ensureAvailable();
    _ensureRoute(request.routeId);
    final location = _locationFor(request.uri);
    if (!canPop()) return _replace(request, location);
    final navigator = _activeNavigator;
    _expectBackendEvent(CCGoRouterNavigationEventKind.pop);
    if (navigator == null || !await navigator.maybePop<Object?>(popResult)) {
      _discardExpectedBackendEvent(CCGoRouterNavigationEventKind.pop);
      throw const CCNavigationAdapterError(
        'GoRouter rejected the popAndPush Pop operation.',
      );
    }
    _removeTrackedEntry();
    return _push(request, location);
  }

  /// Pops tracked entries while the predicate does not match.
  ///
  /// Entries created outside this adapter are not reconstructed as Runtime
  /// route metadata. Observer events for those entries remain diagnostic and
  /// cannot remove adapter-owned entries by stack position.
  @override
  Future<void> popUntil(CCNavigationStackPredicate predicate) async {
    _ensureAvailable();
    final navigator = _activeNavigator;
    if (navigator == null) return;
    while (_entries.length > 1 && !predicate(_entries.last.snapshot)) {
      _expectBackendEvent(CCGoRouterNavigationEventKind.pop);
      final didPop = await navigator.maybePop<Object?>();
      if (!didPop) {
        _discardExpectedBackendEvent(CCGoRouterNavigationEventKind.pop);
        break;
      }
      _removeTrackedEntry();
    }
  }

  /// Pushes [request] after removing tracked entries until [predicate] matches.
  ///
  /// Each removed entry is popped through GoRouter so its page lifecycle and
  /// pending result Future are handled by the backend. The root entry remains
  /// when no tracked entry satisfies the predicate, matching Navigator and
  /// memory-adapter behavior.
  @override
  Future<Object?> pushAndRemoveUntil(
    CCNavigationRequest request,
    CCNavigationStackPredicate predicate,
  ) async {
    _ensureAvailable();
    _ensureRoute(request.routeId);
    while (_entries.length > 1 && !predicate(_entries.last.snapshot)) {
      final navigator = _activeNavigator;
      _expectBackendEvent(CCGoRouterNavigationEventKind.pop);
      if (navigator == null || !await navigator.maybePop<Object?>()) {
        _discardExpectedBackendEvent(CCGoRouterNavigationEventKind.pop);
        throw const CCNavigationAdapterError(
          'GoRouter rejected a pushAndRemoveUntil Pop operation.',
        );
      }
      _removeTrackedEntry();
    }
    return _push(request, _locationFor(request.uri));
  }

  /// Pops the active GoRouter Navigator route with an optional result.
  @override
  void pop({Object? result}) {
    final outcome = popOutcome(result: result);
    if (!outcome.handled) {
      throw const CCNavigationAdapterError(
        'GoRouter has no removable active Navigator route.',
      );
    }
  }

  /// Pops the active GoRouter route and reports backend ownership.
  ///
  /// Navigator observer callbacks are emitted while the adapter's tracked
  /// entries still contain the route, allowing a direct business Pop to
  /// distinguish a foreign Popup/Route from a CCRouter-managed entry.
  @override
  CCPopOutcome popOutcome({Object? result}) {
    _ensureAvailable();
    final navigator = _activeNavigator;
    if (navigator == null || !navigator.canPop()) {
      return const CCPopOutcome(handled: false);
    }
    _lastPoppedBackendEntryId = null;
    _lastPoppedOwner = CCPopRemovedOwner.none;
    _expectBackendEvent(CCGoRouterNavigationEventKind.pop);
    navigator.pop<Object?>(result);
    _discardExpectedBackendEvent(CCGoRouterNavigationEventKind.pop);
    _removeTrackedEntry();
    return CCPopOutcome(
      handled: true,
      removedBackendEntryId: _lastPoppedBackendEntryId,
      removedOwner: _lastPoppedOwner,
      resultAvailable: _lastPoppedOwner == CCPopRemovedOwner.managed,
    );
  }

  /// Returns whether GoRouter can pop its current Navigator stack.
  @override
  bool canPop() {
    _ensureAvailable();
    return _activeNavigator?.canPop() ?? false;
  }

  /// Clears adapter-owned metadata without disposing the application router.
  @override
  Future<void> dispose() async {
    if (_disposed) return;
    _disposed = true;
    _initialized = false;
    for (final remove in _observerRemovers) {
      remove();
    }
    _observerRemovers.clear();
    _backendListeners.clear();
    _routes.clear();
    _runtimeShells.clear();
    _entries.clear();
    _foreignRouteBridge._dispose();
    _backendIdsByNavigationId.clear();
    _expectedBackendEvents.clear();
    _lifecycleEvents.clear();
  }

  /// Pushes one location and removes its tracked entry when it completes.
  Future<Object?> _push(CCNavigationRequest request, String location) {
    final backendEntryId = _nextBackendEntryId();
    _backendIdsByNavigationId[request.navigationId] = backendEntryId;
    final entry = _CCGoRouterEntry(request, backendEntryId);
    _entries.add(entry);
    _expectBackendEvent(CCGoRouterNavigationEventKind.push);
    final result = _router.push<Object?>(location, extra: request.extra);
    result.whenComplete(() {
      _removeTrackedEntry(entry);
      _discardExpectedBackendEvent(CCGoRouterNavigationEventKind.push);
    });
    return result;
  }

  /// Replaces the tracked top entry and delegates the replacement to GoRouter.
  Future<Object?> _replace(CCNavigationRequest request, String location) {
    _removeTrackedEntry();
    final backendEntryId = _nextBackendEntryId();
    _backendIdsByNavigationId[request.navigationId] = backendEntryId;
    final entry = _CCGoRouterEntry(request, backendEntryId);
    _entries.add(entry);
    _expectBackendEvent(CCGoRouterNavigationEventKind.replace);
    final result = _router.replace<Object?>(location, extra: request.extra);
    result.whenComplete(() {
      _removeTrackedEntry(entry);
      _discardExpectedBackendEvent(CCGoRouterNavigationEventKind.replace);
    });
    return result;
  }

  /// Replaces the locally observed stack after a GoRouter location change.
  void _replaceTrackedStack(CCNavigationRequest request) {
    final backendEntryId = _nextBackendEntryId();
    _backendIdsByNavigationId[request.navigationId] = backendEntryId;
    _entries
      ..clear()
      ..add(_CCGoRouterEntry(request, backendEntryId));
  }

  /// Returns or allocates the adapter identity for one backend Route object.
  String _backendEntryIdFor(Route<dynamic> route) =>
      _backendRouteIds[route] ??= _nextBackendEntryId();

  /// Allocates one adapter-scoped backend Entry identity.
  String _nextBackendEntryId() =>
      '$_backendAdapterId-entry-${++_backendEntrySequence}';

  /// Removes one locally observed entry, or the current top entry.
  void _removeTrackedEntry([_CCGoRouterEntry? entry]) {
    if (_entries.isEmpty) return;
    if (entry == null) {
      final removed = _entries.removeLast();
      _backendIdsByNavigationId.remove(removed.request.navigationId);
    } else {
      if (_entries.remove(entry)) {
        _backendIdsByNavigationId.remove(entry.request.navigationId);
      }
    }
  }

  /// Records one backend transition expected from an Adapter-owned operation.
  void _expectBackendEvent(CCGoRouterNavigationEventKind kind) {
    _expectedBackendEvents.add(kind);
  }

  /// Consumes one matching expected transition, if present.
  bool _consumeExpectedBackendEvent(CCGoRouterNavigationEventKind kind) {
    final index = _expectedBackendEvents.indexOf(kind);
    if (index == -1) return false;
    _expectedBackendEvents.removeAt(index);
    return true;
  }

  /// Removes one expected transition when the backend reports no mutation.
  void _discardExpectedBackendEvent(CCGoRouterNavigationEventKind kind) {
    final index = _expectedBackendEvents.indexOf(kind);
    if (index != -1) _expectedBackendEvents.removeAt(index);
  }

  /// Converts an absolute URI into the path location consumed by GoRouter.
  String _locationFor(Uri uri) {
    if (!uri.hasScheme && !uri.hasAuthority) return uri.toString();
    return Uri(
      path: uri.path.isEmpty ? '/' : uri.path,
      query: uri.hasQuery ? uri.query : null,
      fragment: uri.hasFragment ? uri.fragment : null,
    ).toString();
  }

  /// Rejects initialization after permanent adapter disposal.
  void _ensureNotDisposed() {
    if (_disposed) {
      throw const CCNavigationAdapterError(
        'The GoRouter navigation adapter has been disposed.',
      );
    }
  }

  /// Rejects operations before initialization or after disposal.
  void _ensureAvailable() {
    if (!isInitialized) {
      throw const CCNavigationAdapterError(
        'The GoRouter navigation adapter is not active.',
      );
    }
  }

  /// Verifies that Runtime supplied the target route during initialization.
  void _ensureRoute(String routeId) {
    if (!_routes.any((route) => route.routeId == routeId)) {
      throw CCNavigationAdapterError(
        'Route "$routeId" was not supplied to the GoRouter adapter.',
      );
    }
  }

  /// Validates the optional binding set against Runtime route IDs.
  void _validateBindings(Set<String> routeIds) {
    if (_bindings.isEmpty) return;
    final bindingIds = <String>{};
    for (final binding in _bindings) {
      if (!bindingIds.add(binding.routeId)) {
        throw CCNavigationAdapterError(
          'Duplicate GoRouter binding for route "${binding.routeId}".',
        );
      }
      if (!routeIds.contains(binding.routeId)) {
        throw CCNavigationAdapterError(
          'GoRouter binding "${binding.routeId}" has no Runtime route.',
        );
      }
    }
    final missing = routeIds.difference(bindingIds);
    if (missing.isNotEmpty) {
      final ids = missing.toList()..sort();
      throw CCNavigationAdapterError(
        'Runtime routes have no GoRouter binding: ${ids.join(', ')}.',
      );
    }
  }

  /// Finds the application-owned binding for [routeId], if one was supplied.
  CCGoRouterRouteBinding? _bindingFor(String routeId) {
    for (final binding in _bindings) {
      if (binding.routeId == routeId) return binding;
    }
    return null;
  }

  /// Ensures one binding declares the same presentation family as Runtime.
  void _validatePresentationBinding(
    String routeId,
    CCGoRouterPresentationType expected,
  ) {
    final binding = _bindingFor(routeId);
    if (binding != null && binding.presentationType != expected) {
      throw CCNavigationAdapterError(
        'GoRouter binding "$routeId" declares '
        '${binding.presentationType.name}, but Runtime requires '
        '${expected.name}.',
      );
    }
  }

  /// Requires the custom page builder needed to preserve modal semantics.
  void _ensureCustomModalPage(String routeId) {
    final binding = _bindingFor(routeId);
    if (binding == null || !binding.hasCustomPageBuilder) {
      throw CCNavigationAdapterError(
        'Modal route "$routeId" requires a GoRouter binding with a custom '
        'pageBuilder returning the matching CCRouter modal Page.',
      );
    }
  }

  /// Requires a custom page builder when a plain GoRoute builder cannot retain
  /// the route contract's page family, transition, or opacity semantics.
  void _ensureCustomPage(String routeId) {
    final binding = _bindingFor(routeId);
    if (binding == null || !binding.hasCustomPageBuilder) {
      throw CCNavigationAdapterError(
        'Page route "$routeId" requires a GoRouter binding with a custom '
        'pageBuilder returning ccGoRouterPage(...).',
      );
    }
  }

  /// Returns whether a normal GoRoute builder would lose page semantics.
  bool _requiresCustomPage(CCPagePresentation presentation) =>
      presentation.routeType != CCPageRouteType.platformDefault ||
      presentation.transition != CCPageTransitionType.platformDefault ||
      !presentation.opaque ||
      presentation.fullscreenDialog;

  /// Rejects Shell and non-root Outlet metadata until a matching binding is
  /// supplied by the GoRouter Shell integration.
  void _validatePlacement(CCNavigationRoute route) {
    final placement = route.placement;
    if (placement.routeKind == CCRouteKind.shell) {
      throw CCNavigationAdapterError(
        'GoRouter route "${route.routeId}" is a Shell route. Shell '
        'contracts require an application-owned ShellRoute binding.',
      );
    }
    if (placement.navigatorOutlet != 'root' &&
        !_navigatorKeys.containsKey(placement.navigatorOutlet)) {
      throw CCNavigationAdapterError(
        'GoRouter route "${route.routeId}" targets Outlet '
        '"${placement.navigatorOutlet}" without a Navigator key.',
      );
    }
    if (placement.shellId != null &&
        !_shellBindings.any((shell) => shell.shellId == placement.shellId)) {
      throw CCNavigationAdapterError(
        'GoRouter route "${route.routeId}" targets unknown Shell '
        '"${placement.shellId}".',
      );
    }
  }

  /// Retains one backend event for diagnostics without exposing mutable state.
  ///
  /// Only operations initiated by this adapter can be correlated with a
  /// Runtime request. Uncorrelated Dialog, PopupRoute, LocalHistoryEntry, and
  /// application-owned Navigator events are forwarded without reconciling the
  /// managed entry list because their stack identity is not yet known.
  void _recordLifecycleEvent(CCGoRouterNavigationEvent event) {
    if (_disposed) return;
    if (_lifecycleEventCapacity > 0) {
      if (_lifecycleEvents.length == _lifecycleEventCapacity) {
        _lifecycleEvents.removeAt(0);
      }
      _lifecycleEvents.add(event);
    }
    final isAdapterOwned = _consumeExpectedBackendEvent(event.kind);
    if (event.kind == CCGoRouterNavigationEventKind.pop) {
      final backendEntryId = _backendEntryIdFor(event.route);
      _lastPoppedBackendEntryId = backendEntryId;
      _lastPoppedOwner =
          _entries.any((entry) => entry.backendEntryId == backendEntryId)
          ? CCPopRemovedOwner.managed
          : CCPopRemovedOwner.foreign;
    }
    _emitBackendEvent(event, correlateRequest: isAdapterOwned);
  }

  /// Translates a Flutter observer event into the adapter-neutral contract.
  void _emitBackendEvent(
    CCGoRouterNavigationEvent event, {
    required bool correlateRequest,
  }) {
    final request = correlateRequest && _entries.isNotEmpty
        ? _entries.last.request
        : null;
    final trackedBackendEntryId = request == null
        ? null
        : _backendIdsByNavigationId[request.navigationId];
    if (trackedBackendEntryId != null) {
      _backendRouteIds[event.route] = trackedBackendEntryId;
    }
    final backendEntryId =
        trackedBackendEntryId ?? _backendEntryIdFor(event.route);
    final previousBackendEntryId = event.previousRoute == null
        ? null
        : _backendEntryIdFor(event.previousRoute!);
    final operationSequence = ++_backendOperationSequence;
    final backendEvent = CCNavigationBackendEvent(
      kind: switch (event.kind) {
        CCGoRouterNavigationEventKind.push => CCNavigationBackendEventKind.push,
        CCGoRouterNavigationEventKind.pop => CCNavigationBackendEventKind.pop,
        CCGoRouterNavigationEventKind.replace =>
          CCNavigationBackendEventKind.replace,
        CCGoRouterNavigationEventKind.remove =>
          CCNavigationBackendEventKind.remove,
      },
      backendEntryId: backendEntryId,
      backendOperationId: '$_backendAdapterId-operation-$operationSequence',
      previousBackendEntryId: previousBackendEntryId,
      navigatorOutlet: event.outlet,
      sequence: operationSequence,
      owner: request == null
          ? CCBackendEntryOwner.foreign
          : CCBackendEntryOwner.managed,
      navigationId: request?.navigationId,
      routeId: request?.routeId,
      uri: request?.uri,
      placement: request?.placement ?? const CCRoutePlacement.root(),
      location: event.location,
      origin: request?.origin,
      source: request?.source,
      timestamp: DateTime.now(),
    );
    _publishBackendEvent(backendEvent);
  }

  /// Publishes one explicit third-party route transition through the Adapter.
  void _recordForeignBridgeEvent(
    CCNavigationBackendEventKind kind,
    CCGoRouterForeignRouteHandle handle,
    CCGoRouterForeignRouteHandle? previous,
  ) {
    _ensureAvailable();
    final operationSequence = ++_backendOperationSequence;
    _publishBackendEvent(
      CCNavigationBackendEvent(
        kind: kind,
        backendEntryId: handle.backendEntryId,
        backendOperationId: '$_backendAdapterId-operation-$operationSequence',
        previousBackendEntryId: previous?.backendEntryId,
        hostId: handle.hostId,
        navigatorOutlet: handle.navigatorOutlet,
        sequence: operationSequence,
        owner: CCBackendEntryOwner.foreign,
        placement: CCRoutePlacement(navigatorOutlet: handle.navigatorOutlet),
        location: handle.location,
        timestamp: DateTime.now(),
      ),
    );
  }

  /// Flattens one GoRouter match branch while retaining its Navigator Outlet.
  void _collectInitialMatches(
    List<RouteMatchBase> matches,
    List<CCNavigationBackendEntrySnapshot> snapshots, {
    required String outlet,
  }) {
    for (final match in matches) {
      final matchOutlet = match is ShellRouteMatch
          ? _outletForNavigatorKey(match.navigatorKey)
          : outlet;
      snapshots.add(
        CCNavigationBackendEntrySnapshot(
          backendEntryId: _nextBackendEntryId(),
          owner: CCBackendEntryOwner.opaque,
          navigatorOutlet: matchOutlet,
          location: match.matchedLocation,
        ),
      );
      if (match is ShellRouteMatch) {
        _collectInitialMatches(match.matches, snapshots, outlet: matchOutlet);
      }
    }
  }

  /// Resolves an application-owned Navigator key to its configured Outlet.
  String _outletForNavigatorKey(GlobalKey<NavigatorState> key) {
    if (identical(key, _router.routerDelegate.navigatorKey)) return 'root';
    for (final entry in _navigatorKeys.entries) {
      if (identical(entry.value, key)) return entry.key;
    }
    return 'root';
  }

  /// Publishes one opaque UI transition without creating a managed route.
  ///
  /// Opaque surfaces include overlays, menus, `LocalHistoryEntry`, and
  /// third-party popup systems whose lifecycle cannot be represented as a
  /// Navigator `Route`. They remain isolated from RouteEntry and result
  /// bookkeeping while still appearing in backend diagnostics.
  void _recordOpaqueBridgeEvent(
    CCNavigationBackendEventKind kind,
    CCGoRouterOpaqueUiHandle handle,
  ) {
    _ensureAvailable();
    final operationSequence = ++_backendOperationSequence;
    _publishBackendEvent(
      CCNavigationBackendEvent(
        kind: kind,
        backendEntryId: handle.backendEntryId,
        backendOperationId: '$_backendAdapterId-operation-$operationSequence',
        hostId: handle.hostId,
        navigatorOutlet: handle.navigatorOutlet,
        sequence: operationSequence,
        owner: CCBackendEntryOwner.opaque,
        placement: CCRoutePlacement(navigatorOutlet: handle.navigatorOutlet),
        location: handle.location,
        timestamp: DateTime.now(),
      ),
    );
  }

  /// Notifies backend listeners while isolating telemetry failures.
  void _publishBackendEvent(CCNavigationBackendEvent backendEvent) {
    for (final listener in _backendListeners.toList()) {
      try {
        listener(backendEvent);
      } catch (_) {
        // Backend telemetry must never interrupt a Navigator transition.
      }
    }
  }

  /// Validates Shell contracts against application-owned GoRouter bindings.
  void _validateShellBindings(List<CCNavigationShell> contracts) {
    final bindingsById = <String, CCGoRouterShellBinding>{};
    for (final binding in _shellBindings) {
      if (bindingsById.containsKey(binding.shellId)) {
        throw CCNavigationAdapterError(
          'Duplicate GoRouter Shell binding "${binding.shellId}".',
        );
      }
      bindingsById[binding.shellId] = binding;
    }
    final contractIds = contracts.map((shell) => shell.shellId).toSet();
    final unknownBindings = bindingsById.keys.toSet().difference(contractIds);
    if (unknownBindings.isNotEmpty) {
      final ids = unknownBindings.toList()..sort();
      throw CCNavigationAdapterError(
        'GoRouter Shell bindings have no Runtime contract: ${ids.join(', ')}.',
      );
    }
    for (final contract in contracts) {
      final binding = bindingsById[contract.shellId];
      if (binding == null) {
        throw CCNavigationAdapterError(
          'Runtime Shell "${contract.shellId}" has no GoRouter binding.',
        );
      }
      final boundOutlets = binding.outlets.keys.toList();
      if (!_sameOrder(boundOutlets, contract.outlets)) {
        throw CCNavigationAdapterError(
          'GoRouter Shell "${contract.shellId}" Outlet order does not match '
          'the Runtime contract.',
        );
      }
      if (binding.initialOutlet != contract.initialOutlet) {
        throw CCNavigationAdapterError(
          'GoRouter Shell "${contract.shellId}" initial Outlet '
          '"${binding.initialOutlet}" does not match Runtime Outlet '
          '"${contract.initialOutlet}".',
        );
      }
      switch (contract.type) {
        case CCShellType.singleNavigator:
          final route = binding.route;
          if (route is! ShellRoute ||
              binding.outlets.length != 1 ||
              !identical(
                binding.outlets[contract.outlets.single],
                route.navigatorKey,
              )) {
            throw CCNavigationAdapterError(
              'Single-Navigator Shell "${contract.shellId}" must bind its '
              'ShellRoute Navigator key to Outlet '
              '"${contract.outlets.single}".',
            );
          }
          break;
        case CCShellType.statefulBranches:
          final route = binding.route;
          if (route is! StatefulShellRoute ||
              route.branches.length != contract.outlets.length) {
            throw CCNavigationAdapterError(
              'Stateful Shell "${contract.shellId}" must bind one '
              'StatefulShellRoute branch per declared Outlet.',
            );
          }
          for (var index = 0; index < contract.outlets.length; index++) {
            final outlet = contract.outlets[index];
            if (!identical(
              binding.outlets[outlet],
              route.branches[index].navigatorKey,
            )) {
              throw CCNavigationAdapterError(
                'Stateful Shell "${contract.shellId}" branch $index does '
                'not match Outlet "$outlet".',
              );
            }
          }
      }
    }
  }

  /// Compares ordered string identities without allocating converted sets.
  static bool _sameOrder(List<String> first, List<String> second) {
    if (first.length != second.length) return false;
    for (var index = 0; index < first.length; index++) {
      if (first[index] != second[index]) return false;
    }
    return true;
  }

  /// Combines explicit Outlet keys with keys declared by Shell bindings.
  static Map<String, GlobalKey<NavigatorState>> _mergeNavigatorKeys(
    Map<String, GlobalKey<NavigatorState>> explicit,
    Iterable<CCGoRouterShellBinding> shells,
  ) {
    final merged = <String, GlobalKey<NavigatorState>>{...explicit};
    for (final shell in shells) {
      for (final entry in shell.outlets.entries) {
        final existing = merged[entry.key];
        if (existing != null && !identical(existing, entry.value)) {
          throw ArgumentError.value(
            entry.key,
            'navigatorKeys',
            'Outlet is declared with different Navigator keys.',
          );
        }
        merged[entry.key] = entry.value;
      }
    }
    return Map.unmodifiable(merged);
  }

  /// Finds the Navigator belonging to the currently tracked route.
  NavigatorState? get _activeNavigator {
    final key = _entries.isEmpty
        ? null
        : _navigatorKeys[_entries.last.request.placement.navigatorOutlet];
    return key?.currentState ??
        _router.routerDelegate.navigatorKey.currentState;
  }
}

/// Internal snapshot used by stack predicates without exposing GoRouter types.
final class _CCGoRouterEntry {
  /// Creates a tracked entry from one accepted navigation request.
  _CCGoRouterEntry(this.request, this.backendEntryId);

  /// Request that created this tracked entry.
  final CCNavigationRequest request;

  /// Backend identity associated with the GoRouter Route for this entry.
  final String backendEntryId;

  /// Adapter-neutral identity supplied to a stack predicate.
  CCNavigationEntry get snapshot => CCNavigationEntry(
    navigationId: request.navigationId,
    routeId: request.routeId,
    uri: request.uri,
  );
}
