import 'package:ccrouter/ccrouter.dart';
import 'package:flutter/widgets.dart';
import 'package:go_router/go_router.dart';

import 'route_binding.dart';

/// Adapts CCRouter navigation requests to an externally configured [GoRouter].
///
/// The application owns the [router] and supplies its `GoRoute` page builders.
/// This adapter only translates validated CCRouter operations; it does not
/// generate page widgets, retain a global `BuildContext`, or dispose the
/// externally supplied router. GoRouter route paths should match the primary
/// path patterns generated by the registered route contracts.
///
/// Modal bottom sheets and dialogs are supported when their bound [GoRoute]
/// supplies a custom `pageBuilder` returning the corresponding exported modal
/// Page type. The adapter does not rewrite application-owned GoRoutes.
final class CCGoRouterAdapter implements CCNavigationAdapter {
  /// Creates an adapter around an application-owned [router].
  CCGoRouterAdapter({
    required GoRouter router,
    Iterable<CCGoRouterRouteBinding> bindings = const [],
    Map<String, GlobalKey<NavigatorState>> navigatorKeys = const {},
  }) : _router = router,
       _bindings = List.unmodifiable(bindings),
       _navigatorKeys = Map.unmodifiable(navigatorKeys);

  /// GoRouter instance that receives translated navigation operations.
  GoRouter get router => _router;

  /// Application-owned GoRouter backend.
  final GoRouter _router;

  /// Component route bindings used to validate the application route table.
  final List<CCGoRouterRouteBinding> _bindings;

  /// Application-owned Navigator keys indexed by CCRouter Outlet name.
  final Map<String, GlobalKey<NavigatorState>> _navigatorKeys;

  /// Route metadata accepted by the Runtime during initialization.
  final List<CCNavigationRoute> _routes = [];

  /// Entries observed through operations issued by this adapter.
  final List<_CCGoRouterEntry> _entries = [];

  /// Whether [initialize] completed successfully.
  bool _initialized = false;

  /// Whether [dispose] permanently closed the adapter.
  bool _disposed = false;

  /// Whether the adapter is initialized and has not been disposed.
  bool get isInitialized => _initialized && !_disposed;

  /// Immutable route metadata accepted during initialization.
  List<CCNavigationRoute> get routes => List.unmodifiable(_routes);

  /// Application-owned GoRouter bindings supplied for Runtime route IDs.
  List<CCGoRouterRouteBinding> get bindings => _bindings;

  /// Navigator keys used to resolve explicit non-root Outlet targets.
  Map<String, GlobalKey<NavigatorState>> get navigatorKeys => _navigatorKeys;

  /// Initializes the adapter with Runtime-validated route metadata.
  ///
  /// The adapter validates presentation capabilities before accepting any
  /// navigation. GoRouter remains responsible for matching and rendering the
  /// application's concrete `GoRoute` tree.
  @override
  Future<void> initialize(List<CCNavigationRoute> routes) async {
    _ensureNotDisposed();
    if (_initialized) {
      throw const CCNavigationAdapterError(
        'The GoRouter navigation adapter is already initialized.',
      );
    }
    final routeIds = <String>{};
    for (final route in routes) {
      if (!routeIds.add(route.routeId)) {
        throw CCNavigationAdapterError(
          'Duplicate route ID "${route.routeId}" supplied to GoRouter.',
        );
      }
      switch (route.presentation) {
        case CCPagePresentation():
          _validatePresentationBinding(
            route.routeId,
            CCGoRouterPresentationKind.page,
          );
          break;
        case CCModalBottomSheetPresentation():
          _validatePresentationBinding(
            route.routeId,
            CCGoRouterPresentationKind.bottomSheet,
          );
          _ensureCustomModalPage(route.routeId);
          break;
        case CCDialogPresentation():
          _validatePresentationBinding(
            route.routeId,
            CCGoRouterPresentationKind.dialog,
          );
          _ensureCustomModalPage(route.routeId);
      }
      _validatePlacement(route);
    }
    _validateBindings(routeIds);
    _routes
      ..clear()
      ..addAll(routes);
    _initialized = true;
  }

  /// Executes one validated request through GoRouter.
  @override
  Future<Object?> navigate(CCNavigationRequest request) {
    _ensureAvailable();
    _ensureRoute(request.routeId);
    final location = _locationFor(request.uri);
    switch (request.operation) {
      case CCNavigationOperation.push:
        return _push(request, location);
      case CCNavigationOperation.replace:
        return _replace(request, location);
      case CCNavigationOperation.go:
      case CCNavigationOperation.reset:
      case CCNavigationOperation.open:
        _router.go(location, extra: request.extra);
        _replaceTrackedStack(request);
        return Future<Object?>.value();
      case CCNavigationOperation.popAndPush:
      case CCNavigationOperation.pushAndRemoveUntil:
        throw const CCNavigationAdapterError(
          'Composite operations must use their dedicated Adapter method.',
        );
    }
  }

  /// Attempts to pop the active GoRouter Navigator route.
  @override
  Future<bool> maybePop({Object? result}) async {
    _ensureAvailable();
    final navigator = _activeNavigator;
    if (navigator == null) return false;
    final didPop = await navigator.maybePop<Object?>(result);
    if (didPop) _removeTrackedEntry();
    return didPop;
  }

  /// Pops the active entry and pushes [request] through GoRouter.
  ///
  /// GoRouter exposes no single public operation with this exact contract, so
  /// the adapter performs the Pop through GoRouter's active Navigator and then
  /// issues its imperative Push. The removed entry receives [popResult].
  @override
  Future<Object?> popAndPush(
    CCNavigationRequest request, {
    Object? popResult,
  }) async {
    _ensureAvailable();
    _ensureRoute(request.routeId);
    final location = _locationFor(request.uri);
    if (!canPop()) return _replace(request, location);
    final navigator = _activeNavigator;
    if (navigator == null || !await navigator.maybePop<Object?>(popResult)) {
      throw const CCNavigationAdapterError(
        'GoRouter rejected the popAndPush Pop operation.',
      );
    }
    _removeTrackedEntry();
    return _push(request, location);
  }

  /// Pops tracked entries while the predicate does not match.
  ///
  /// Entries created outside this adapter are not visible to the predicate
  /// until the adapter receives a backend lifecycle bridge.
  @override
  Future<void> popUntil(CCNavigationStackPredicate predicate) async {
    _ensureAvailable();
    final navigator = _activeNavigator;
    if (navigator == null) return;
    while (_entries.length > 1 && !predicate(_entries.last.snapshot)) {
      final didPop = await navigator.maybePop<Object?>();
      if (!didPop) break;
      _removeTrackedEntry();
    }
  }

  /// Pushes [request] after removing tracked entries until [predicate] matches.
  ///
  /// Each removed entry is popped through GoRouter so its page lifecycle and
  /// pending result Future are handled by the backend. The root entry remains
  /// when no tracked entry satisfies the predicate, matching Navigator and
  /// memory-adapter behavior.
  @override
  Future<Object?> pushAndRemoveUntil(
    CCNavigationRequest request,
    CCNavigationStackPredicate predicate,
  ) async {
    _ensureAvailable();
    _ensureRoute(request.routeId);
    while (_entries.length > 1 && !predicate(_entries.last.snapshot)) {
      final navigator = _activeNavigator;
      if (navigator == null || !await navigator.maybePop<Object?>()) {
        throw const CCNavigationAdapterError(
          'GoRouter rejected a pushAndRemoveUntil Pop operation.',
        );
      }
      _removeTrackedEntry();
    }
    return _push(request, _locationFor(request.uri));
  }

  /// Pops the active GoRouter Navigator route with an optional result.
  @override
  void pop({Object? result}) {
    _ensureAvailable();
    final navigator = _activeNavigator;
    if (navigator == null) {
      throw const CCNavigationAdapterError(
        'GoRouter has no active Navigator for the current Outlet.',
      );
    }
    navigator.pop<Object?>(result);
    _removeTrackedEntry();
  }

  /// Returns whether GoRouter can pop its current Navigator stack.
  @override
  bool canPop() {
    _ensureAvailable();
    return _activeNavigator?.canPop() ?? false;
  }

  /// Clears adapter-owned metadata without disposing the application router.
  @override
  Future<void> dispose() async {
    if (_disposed) return;
    _disposed = true;
    _initialized = false;
    _routes.clear();
    _entries.clear();
  }

  /// Pushes one location and removes its tracked entry when it completes.
  Future<Object?> _push(CCNavigationRequest request, String location) {
    final entry = _CCGoRouterEntry(request);
    _entries.add(entry);
    final result = _router.push<Object?>(location, extra: request.extra);
    result.whenComplete(() => _removeTrackedEntry(entry));
    return result;
  }

  /// Replaces the tracked top entry and delegates the replacement to GoRouter.
  Future<Object?> _replace(CCNavigationRequest request, String location) {
    _removeTrackedEntry();
    final entry = _CCGoRouterEntry(request);
    _entries.add(entry);
    final result = _router.replace<Object?>(location, extra: request.extra);
    result.whenComplete(() => _removeTrackedEntry(entry));
    return result;
  }

  /// Replaces the locally observed stack after a GoRouter location change.
  void _replaceTrackedStack(CCNavigationRequest request) {
    _entries
      ..clear()
      ..add(_CCGoRouterEntry(request));
  }

  /// Removes one locally observed entry, or the current top entry.
  void _removeTrackedEntry([_CCGoRouterEntry? entry]) {
    if (_entries.isEmpty) return;
    if (entry == null) {
      _entries.removeLast();
    } else {
      _entries.remove(entry);
    }
  }

  /// Converts an absolute URI into the path location consumed by GoRouter.
  String _locationFor(Uri uri) {
    if (!uri.hasScheme && !uri.hasAuthority) return uri.toString();
    return Uri(
      path: uri.path.isEmpty ? '/' : uri.path,
      query: uri.hasQuery ? uri.query : null,
      fragment: uri.hasFragment ? uri.fragment : null,
    ).toString();
  }

  /// Rejects initialization after permanent adapter disposal.
  void _ensureNotDisposed() {
    if (_disposed) {
      throw const CCNavigationAdapterError(
        'The GoRouter navigation adapter has been disposed.',
      );
    }
  }

  /// Rejects operations before initialization or after disposal.
  void _ensureAvailable() {
    if (!isInitialized) {
      throw const CCNavigationAdapterError(
        'The GoRouter navigation adapter is not active.',
      );
    }
  }

  /// Verifies that Runtime supplied the target route during initialization.
  void _ensureRoute(String routeId) {
    if (!_routes.any((route) => route.routeId == routeId)) {
      throw CCNavigationAdapterError(
        'Route "$routeId" was not supplied to the GoRouter adapter.',
      );
    }
  }

  /// Validates the optional binding set against Runtime route IDs.
  void _validateBindings(Set<String> routeIds) {
    if (_bindings.isEmpty) return;
    final bindingIds = <String>{};
    for (final binding in _bindings) {
      if (!bindingIds.add(binding.routeId)) {
        throw CCNavigationAdapterError(
          'Duplicate GoRouter binding for route "${binding.routeId}".',
        );
      }
      if (!routeIds.contains(binding.routeId)) {
        throw CCNavigationAdapterError(
          'GoRouter binding "${binding.routeId}" has no Runtime route.',
        );
      }
    }
    final missing = routeIds.difference(bindingIds);
    if (missing.isNotEmpty) {
      final ids = missing.toList()..sort();
      throw CCNavigationAdapterError(
        'Runtime routes have no GoRouter binding: ${ids.join(', ')}.',
      );
    }
  }

  /// Finds the application-owned binding for [routeId], if one was supplied.
  CCGoRouterRouteBinding? _bindingFor(String routeId) {
    for (final binding in _bindings) {
      if (binding.routeId == routeId) return binding;
    }
    return null;
  }

  /// Ensures one binding declares the same presentation family as Runtime.
  void _validatePresentationBinding(
    String routeId,
    CCGoRouterPresentationKind expected,
  ) {
    final binding = _bindingFor(routeId);
    if (binding != null && binding.presentationKind != expected) {
      throw CCNavigationAdapterError(
        'GoRouter binding "$routeId" declares '
        '${binding.presentationKind.name}, but Runtime requires '
        '${expected.name}.',
      );
    }
  }

  /// Requires the custom page builder needed to preserve modal semantics.
  void _ensureCustomModalPage(String routeId) {
    final binding = _bindingFor(routeId);
    if (binding == null || !binding.hasCustomPageBuilder) {
      throw CCNavigationAdapterError(
        'Modal route "$routeId" requires a GoRouter binding with a custom '
        'pageBuilder returning the matching CCRouter modal Page.',
      );
    }
  }

  /// Rejects Shell and non-root Outlet metadata until a matching binding is
  /// supplied by the GoRouter Shell integration.
  void _validatePlacement(CCNavigationRoute route) {
    final placement = route.placement;
    if (placement.routeKind == CCRouteKind.shell) {
      throw CCNavigationAdapterError(
        'GoRouter route "${route.routeId}" is a Shell route. Shell '
        'contracts require an application-owned ShellRoute binding.',
      );
    }
    if (placement.navigatorOutlet != 'root' &&
        !_navigatorKeys.containsKey(placement.navigatorOutlet)) {
      throw CCNavigationAdapterError(
        'GoRouter route "${route.routeId}" targets Outlet '
        '"${placement.navigatorOutlet}" without a Navigator key.',
      );
    }
  }

  /// Finds the Navigator belonging to the currently tracked route.
  NavigatorState? get _activeNavigator {
    final key = _entries.isEmpty
        ? null
        : _navigatorKeys[_entries.last.request.placement.navigatorOutlet];
    return key?.currentState ??
        _router.routerDelegate.navigatorKey.currentState;
  }
}

/// Internal snapshot used by stack predicates without exposing GoRouter types.
final class _CCGoRouterEntry {
  /// Creates a tracked entry from one accepted navigation request.
  _CCGoRouterEntry(this.request);

  /// Request that created this tracked entry.
  final CCNavigationRequest request;

  /// Adapter-neutral identity supplied to a stack predicate.
  CCNavigationEntry get snapshot => CCNavigationEntry(
    navigationId: request.navigationId,
    routeId: request.routeId,
    uri: request.uri,
  );
}
