builders:
  route_contracts:
    import: "package:ccrouter_generator/builder.dart"
    builder_factories: ["ccRouteContractBuilder"]
    build_extensions:
      "^lib/src/{{}}.dart": ["lib/src/ccrouter_generated/contract/{{}}.route.contract.g.dart"]
    auto_apply: dependents
    build_to: source
    runs_before: ["ccrouter_generator:routes", "ccrouter_generator:route_metadata"]
    defaults:
      generate_for:
        exclude: ["lib/**/ccrouter_generated/**"]
  routes:
    import: "package:ccrouter_generator/builder.dart"
    builder_factories: ["ccRouteBuilder"]
    build_extensions:
      "^lib/src/{{}}.dart": ["lib/src/ccrouter_generated/route/{{}}.route.g.dart"]
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        exclude: ["lib/**/ccrouter_generated/**"]
  route_bindings:
    import: "package:ccrouter_generator/builder.dart"
    builder_factories: ["ccRouteBindingBuilder"]
    build_extensions:
      "^lib/src/{{}}.dart": ["lib/src/ccrouter_generated/binding/{{}}.route_binding.g.dart"]
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        exclude: ["lib/**/ccrouter_generated/**"]
  components:
    import: "package:ccrouter_generator/builder.dart"
    builder_factories: ["ccComponentBuilder"]
    build_extensions:
      "^lib/src/{{}}.dart": ["lib/src/ccrouter_generated/component/{{}}.component.g.dart"]
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        exclude: ["lib/**/ccrouter_generated/**"]
  component_metadata:
    import: "package:ccrouter_generator/builder.dart"
    builder_factories: ["ccComponentMetadataBuilder"]
    build_extensions:
      "^lib/{{}}.dart": ["lib/src/ccrouter_generated/metadata/{{}}.component.json"]
    auto_apply: dependents
    build_to: cache
    defaults:
      generate_for:
        exclude: ["lib/**/ccrouter_generated/**"]
  route_metadata:
    import: "package:ccrouter_generator/builder.dart"
    builder_factories: ["ccRouteMetadataBuilder"]
    build_extensions:
      "^lib/{{}}.dart": ["lib/src/ccrouter_generated/metadata/{{}}.route.json"]
    auto_apply: dependents
    build_to: cache
    defaults:
      generate_for:
        exclude: ["lib/**/ccrouter_generated/**"]
