name: ccrouter_demo
description: Flutter development app for CCRouter.
publish_to: none
resolution: workspace
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  app_links: ^7.0.0
  ccrouter: ^0.1.0
  ccrouter_go_router: ^0.1.0
  demo_order: ^0.1.0
  demo_order_contracts: ^0.1.0
  demo_payment: ^0.1.0
  demo_navigation_lab: ^0.1.0
  demo_web: ^0.1.0
  demo_web_contracts: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
